# Generated by Django 4.1.6 on 2023-02-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Сделано')], default='new', max_length=30, verbose_name='Статус')),
                ('date_to_do', models.CharField(help_text='YYYY-mm-dd', max_length=10, verbose_name='Дата выполнения')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Описание')),
            ],
        ),
    ]
